spring:
  datasource:
    url: jdbc:postgresql://monitoring-management-database:5432/monitoring-management
    # url: jdbc:postgresql://localhost:5432/monitoring-management
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    # addresses: localhost:5672
    host: rabbit
server:
  port: 8082

security:
  jwt:
    secret-key: p27hQF7rs3OCVAVNn6ovnP0hAM4bY2HvcRasLP1KiI6U5Rg7tV3eNdjBdSjGDleq

#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.web.socket: DEBUG
